name: Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write  # Ensures the necessary permissions for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true  # Improves performance by caching installed gems.
      
      - name: Set up Pages
        uses: actions/configure-pages@v3
      
      - name: Build Site
        run: bundle exec jekyll build --baseurl "${{ github.event.repository.name }}"
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          name: github-pages
          path: ./_site 
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
