name: Pages

on:
  push:
    branches:
      - main # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or the version you are using.
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build --baseurl "${{ github.event.repository.name }}"
      - uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          artifact_dir: ./_site